compe_site/urls.py
from django.urls import path

from . import views

app_name = "compe_site"

urlpatterns = [
    path("", views.RankingView, name="index"),
    path('signup/', views.SignupView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path("ranking/",views.RankingView,name="ranking"),
    path("postresult/",views.upload_result,name="post_result"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("compe_site.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compe_site/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager,
                                        AbstractBaseUser,
                                        PermissionsMixin)
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, account_id, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, account_id=account_id, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, account_id, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )

    def create_superuser(self, email, account_id, password, **extra_fields):
        extra_fields['is_active'] = True
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(
            email=email,
            account_id=account_id,
            password=password,
            **extra_fields,
        )


class User(AbstractBaseUser, PermissionsMixin):

    account_id = models.CharField(
        verbose_name=_("学籍番号"),
        unique=True,
        max_length=10
    )
    email = models.EmailField(
        verbose_name=_("email"),
        unique=True
    )
    first_name = models.CharField(
        verbose_name=_("first_name"),
        max_length=150,
        null=True,
        blank=True
    )
    last_name = models.CharField(
        verbose_name=_("last_name"),
        max_length=150,
        null=True,
        blank=True
    )
    birth_date = models.DateField(
        verbose_name=_("birth_date"),
        blank=True,
        null=True
    )
    is_superuser = models.BooleanField(
        verbose_name=_("is_superuer"),
        default=False
    )
    is_staff = models.BooleanField(
        verbose_name=_('staff status'),
        default=False,
    )
    is_active = models.BooleanField(
        verbose_name=_('active'),
        default=True,
    )
    created_at = models.DateTimeField(
        verbose_name=_("created_at"),
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name=_("updateded_at"),
        auto_now=True
    )

    objects = UserManager()

    USERNAME_FIELD = 'account_id' # ログイン時、ユーザー名の代わりにaccount_idを使用
    REQUIRED_FIELDS = ['email']  # スーパーユーザー作成時にemailも設定する

    def __str__(self):
        return self.account_id

class CSV(models.Model):
    csv = models.FileField(upload_to='media/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    
class Ranking(models.Model):
    account_id = models.CharField(
        verbose_name=_("学籍番号"),
        unique=True,
        max_length=10
    )
    score = models.FloatField(
        verbose_name=_("得点"),
    )
    created_at = models.DateTimeField(
        verbose_name=_("作成日"),
        auto_now_add=True
    )
    def __str__(self):
        return self.account_id

compe_site/forms.py
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm# 追加
from django.core.validators import FileExtensionValidator
from django import forms

from .models import User,CSV

class LoginFrom(AuthenticationForm):
    class Meta:
        model = User

class CsvForm(forms.Form):
    file = forms.FileField(label='CSVファイル',validators=[FileExtensionValidator(['csv'])])

#formをforms.Formkらforms.ModelFormにすると、なぜかValidationエラーになりis_validを突破できない。
#modelformじゃないとupload_toを指定できない
class CsvModelForm(forms.ModelForm):
    class Meta:
        model = CSV
        fields = ['csv']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "account_id",
            "email",
            # "first_name",
            # "last_name",
            # "birth_date",
        )

compe_site/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.views.generic import TemplateView,CreateView
from .forms import LoginFrom
from django.contrib.auth.views import LoginView as BaseLoginView, LogoutView as BaseLogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
import pandas as pd
from .forms import CsvForm,SignUpForm,CsvModelForm
from .models import Ranking
from django.conf import settings
import datetime
from sklearn.metrics import accuracy_score
import os

class IndexView(LoginRequiredMixin,TemplateView):
    template_name = "compe_site/ranking.html"
    login_url = '/login/'

def RankingView(request):
    top_rankings = Ranking.objects.order_by('-score')[:20]  # スコアが高い順に10件取得
    context = {'top_rankings': top_rankings}
    print(context)
    return render(request, 'compe_site/ranking.html',context)

class SignupView(CreateView):
    """ ユーザー登録用ビュー """
    form_class = SignUpForm # 作成した登録用フォームを設定
    template_name = "compe_site/signup.html" 
    success_url = reverse_lazy("compe_site:index") # ユーザー作成後のリダイレクト先ページ

    def form_valid(self, form):
        # ユーザー作成後にそのままログイン状態にする設定
        response = super().form_valid(form)
        account_id = form.cleaned_data.get("account_id")
        password = form.cleaned_data.get("password1")
        user = authenticate(account_id=account_id, password=password)
        login(self.request, user)
        return response

class LoginView(BaseLoginView):
    form_class = LoginFrom
    template_name = "compe_site/login.html"

class LogoutView(BaseLogoutView):
    success_url = reverse_lazy("compe_site:index")

csv_folder_path = f"{settings.MEDIA_ROOT}/compe_site/users_csv"  # フォルダのパスを指定

def upload_result(request):
    #正解データを用意
    ture_df = pd.read_csv(f"{settings.MEDIA_ROOT}/correct_data/result.csv")
    true = ture_df["answer"].values.astype("int8") [:10] 
    if request.method == 'POST':
        form = CsvForm(request.POST,request.FILES)
        # form = CsvModelForm(request.POST,request.FILES)
        if form.is_valid():
            csv_file = request.FILES['file']
            pred_df = pd.read_csv(csv_file)
            user_csv_folder_path = os.path.join(csv_folder_path,request.user.account_id)

            if not os.path.exists(user_csv_folder_path):
                os.makedirs(user_csv_folder_path)
                pred_df.to_csv(f'{user_csv_folder_path}/{request.user.account_id}_{datetime.datetime.now()}.csv')
            else:
                print(f'{user_csv_folder_path}/{request.user.account_id}_{datetime.datetime.now()}.csv')
                pred_df.to_csv(f'{user_csv_folder_path}/{request.user.account_id}_{datetime.datetime.now()}.csv')

            pred = pred_df["answer"].values.astype("int8") [:10] 
            #numpy配列が空の場合accuracy_scoreが計算できない
            if pred.size == 0:
                print("空でした")
                return redirect('compe_site:ranking')  
            else:
                score = accuracy_score(true, pred) #実際のスコアの計算

            new_score = score * 100

            # Rankingモデルに存在する学籍番号を取得
            existing_student = Ranking.objects.filter(account_id=request.user.account_id).first()
            print(existing_student)
            # Rankingモデルにデータがある場合はScoreが大き方を保存、ない場合は追加
            if existing_student:
                if existing_student.score < new_score:
                    existing_student.score = new_score
                    existing_student.save()
                else:
                    # 既存の成績が大きい場合は新しいデータを無視
                    print('既存の成績が高いため、新しいデータを追加しませんでした。')
            else:
                # 学籍番号が存在しない場合は新しいデータを追加
                new_account = Ranking(account_id=request.user.account_id, score=new_score)
                new_account.save()
            
            return redirect('compe_site:ranking')  # ランキングページにリダイレクト
        else:
           print(form.errors.as_data())
           print("ダメです")
    else:
        form = CsvForm()

    return render(request, 'compe_site/post_result.html', {'form': form})

templates/compe_site/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>久留米工業大学データサイエンス部</title>
  <link rel="stylesheet" href='{% static "compe_site/css/styles.css" %}'/> 
</head>
<body class="w-auto">
  <header class="shadow-sm bg-white pt-4">
    <div class="container">
      <div class="row">
        <div class="col fs-3 text-black-60 pb-3">
          久留米工業大学　データサイエンス部
        </div>
        <div class="col-md-auto">
          
        </div>
        <div class="col col-lg-2">
          {% if user.is_authenticated %}
          <div class="fs-5">{{ user.account_id }} さん</div>
          {% endif %}
        </div>
        <div class="col col-lg-2">
          {% if user.is_authenticated %}
          <form action="{% url 'compe_site:logout' %}" method="post" name="f_logout">
            {% csrf_token %}
            <input type="hidden" value="logout">
            <button type="button" class="btn btn-outline-secondary">
              <a href="javascript:f_logout.submit()" class="logout nav-link">Logout</a>
            </button>
          </form>
          {% else %}
          <button type="button" class="btn btn-outline-secondary">
            <a href="{% url 'compe_site:login' %}" class="logout nav-link">Login</a>
          </button>
          {% endif %}
        </div>
      </div>
    </div>
  </header>
  <div class="compe-tabs w-25 mx-auto">
    <ul class="nav nav-tabs pt-4 mx-auto">
      {% if request.path == '/' %}
      <li class="nav-item">
        <a class="nav-link fs-5 active" href="{% url 'compe_site:ranking' %}">ランキング</a>
      </li>
      <li class="nav-item">
        <a class="nav-link fs-5 link-secondary border-bottom-0 border-white" href="{% url 'compe_site:post_result' %}">結果を投稿</a>
      </li>
      {% elif request.path == '/ranking/' %}
      <li class="nav-item">
        <a class="nav-link fs-5 active" href="{% url 'compe_site:ranking' %}">ランキング</a>
      </li>
      <li class="nav-item">
        <a class="nav-link fs-5 link-secondary border-bottom-0 border-white" href="{% url 'compe_site:post_result' %}">結果を投稿</a>
      </li>
      {% elif request.path == '/postresult/' %}
      <li class="nav-item">
        <a class="nav-link fs-5 link-secondary border-bottom-0 border-white" href="{% url 'compe_site:ranking' %}">ランキング</a>
      </li>
      <li class="nav-item">
        <a class="nav-link fs-5 active" href="{% url 'compe_site:post_result' %}">結果を投稿</a>
      </li>
      {% endif %}
    </ul>
  </div> 
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

templates/compe_site/login.html
{% load django_bootstrap5 %}

{% block title %}
<div class="h1">Login</div>
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>
{% endblock %}

templates/compe_site/post_history.html
{% extends 'compe_site/base.html' %}

{% block content %}
<div class="postresult w-75 bg-white mx-auto rounded shadow-sm">
    <div class="p-2">
      <p class="fs-3">結果を投稿してください。</p>
      {% if user.is_authenticated %}
      <form enctype="multipart/form-data" method='POST'>
        {% csrf_token %}
        <div class="">
          {{form.file}}
        </div>
        <br/>
        <button type="submit" class="btn btn-outline-secondary">送信</button>
      </form>
      {% else %}
      <p class="text-center fs-3">ログインしてください。</p>
      {% endif %}
    </div>
    {% if form.errors %}
    <ul>
    {% for error in form.file.errors %}
        <li>{{ error }}</li><!--form内にエラーがある際に表示させる-->
    {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

templates/compe_site/post_result.html
{% extends 'compe_site/base.html' %}

{% block content %}
<div class="postresult w-75 bg-white mx-auto rounded shadow-sm">
    <div class="p-2">
      <p class="fs-3">結果を投稿してください。</p>
      {% if user.is_authenticated %}
      <form enctype="multipart/form-data" method='POST'>
        {% csrf_token %}
        <div class="">
          {{form.file}}
        </div>
        <br/>
        <button type="submit" class="btn btn-outline-secondary">送信</button>
      </form>
      {% else %}
      <p class="text-center fs-3">ログインしてください。</p>
      {% endif %}
    </div>
    {% if form.errors %}
    <ul>
    {% for error in form.file.errors %}
        <li>{{ error }}</li><!--form内にエラーがある際に表示させる-->
    {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

templates/compe_site/ranking.html
{% extends 'compe_site/base.html' %}
{% block content %}

<div class="ranking w-75 mx-auto">
  <table class="table table-hover bg-white rounded shadow-sm">
    <tr>
        <th>順位</th>
        <th>学籍番号</th>
        <th>得点</th>
        <th>投稿日</th>
    </tr>
    {% for ranking in top_rankings %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ ranking.account_id }}</td>
        <td>{{ ranking.score }}</td>
        <td>{{ ranking.created_at }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/compe_site/signup.html
{% block title %}
<div class="h1">新しいアカウントの作成</div>
{% endblock %}

{% block content %}
<div>
  <br>
  <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
    {{ field.label }}
    {{ field }}
    {{ field.errors }}
    <br>
    {% endfor %}
    <div class="mt-3">
      <button type="submit" class="btn btn-primary">Create</button>
      <a href="{% url 'compe_site:index' %}" class="btn btn-secondary">Back</a>
    </div>
  </form>
</div>
{% endblock %}